import React, { useState } from 'react';
import MainFilterSearchBox from '../../components/flight-list/flight-list-v1/MainFilterSearchBox';
import FlightProperties from '../../components/flight-list/flight-list-v1/FlightProperties';
import { transformFlightData } from '../../utils/flight-helpers';

const FlightSearchDemo = () => {
  const [searchResults, setSearchResults] = useState(null);
  const [loading, setLoading] = useState(false);

  const handleSearchResults = (results) => {
    setSearchResults(results);
  };

  const handleDemoSearch = () => {
    setLoading(true);
    
    // Simulate search with faker
    setTimeout(() => {
      try {
        // Import faker services
        import('../../services/flightSearchFaker').then(flightSearchFaker => {
          import('../../services/routeSpecificFaker').then(routeSpecificFaker => {
            // Generate demo search results
            const results = routeSpecificFaker.default.generateBOMToDELSearch('2025-10-15', '2025-10-20');
            const transformedData = transformFlightData(results);
            setSearchResults(transformedData);
            setLoading(false);
          });
        });
      } catch (error) {
        console.error('Demo search failed:', error);
        setLoading(false);
      }
    }, 2000);
  };

  return (
    <div className="container mt-5">
      <div className="row">
        <div className="col-12">
          <h2 className="mb-4">Flight Search Demo</h2>
          <p className="mb-4">This demo shows how the faker generates realistic flight search results without any backend API calls.</p>
          
          {/* Search Form */}
          <div className="card mb-4">
            <div className="card-header">
              <h5>Search Flights</h5>
            </div>
            <div className="card-body">
              <MainFilterSearchBox onSearchResults={handleSearchResults} />
            </div>
          </div>

          {/* Demo Button */}
          <div className="card mb-4">
            <div className="card-header">
              <h5>Demo Search (BOM-DEL Round Trip)</h5>
            </div>
            <div className="card-body">
              <button 
                className="btn btn-primary"
                onClick={handleDemoSearch}
                disabled={loading}
              >
                {loading ? 'Generating Demo Results...' : 'Generate Demo Results'}
              </button>
            </div>
          </div>

          {/* Search Results */}
          {searchResults && (
            <div className="card">
              <div className="card-header">
                <h5>Search Results ({searchResults.length} flights found)</h5>
              </div>
              <div className="card-body">
                <FlightProperties flights={searchResults} loading={false} />
              </div>
            </div>
          )}

          {/* Instructions */}
          <div className="card mt-4">
            <div className="card-header">
              <h5>How it Works</h5>
            </div>
            <div className="card-body">
              <ul>
                <li><strong>No API Calls:</strong> All data is generated by the faker service</li>
                <li><strong>Realistic Data:</strong> Uses real airport codes, airline names, and flight numbers</li>
                <li><strong>Route-Specific:</strong> Indian domestic routes get optimized data</li>
                <li><strong>One-Way & Round-Trip:</strong> Supports both trip types</li>
                <li><strong>Local Storage:</strong> Results are stored locally for the flight list page</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default FlightSearchDemo;

